name: 构建大六壬排盘解析系统APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.24.5"
        channel: "stable"
        
    - name: 获取Flutter依赖
      run: |
        cd LiurenMobileApp
        flutter pub get
        
    - name: 构建APK
      run: |
        cd LiurenMobileApp
        flutter build apk --release
        
    - name: 上传APK到Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 大六壬排盘解析系统-APK
        path: LiurenMobileApp/build/app/outputs/flutter-apk/app-release.apk
